"""initial schema

Revision ID: 8635b867c1c3
Revises:
Create Date: 2026-08-10 01:13:52.439113+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8635b867c1c3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("storage_backend", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=127), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes >= 0", name="ck_assets_size_nonnegative"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key", name="uq_assets_storage_key"),
    )
    op.create_index(op.f("ix_assets_content_sha256"), "assets", ["content_sha256"], unique=False)
    op.create_index("ix_assets_owner_created", "assets", ["owner_id", "created_at"], unique=False)
    op.create_index(op.f("ix_assets_owner_id"), "assets", ["owner_id"], unique=False)
    op.create_index("ix_assets_owner_status", "assets", ["owner_id", "status"], unique=False)
    op.create_table(
        "benchmark_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("git_dirty", sa.Boolean(), nullable=True),
        sa.Column("hardware", sa.String(length=255), nullable=True),
        sa.Column("cpu_model", sa.String(length=255), nullable=True),
        sa.Column("cpu_count", sa.Integer(), nullable=True),
        sa.Column("total_ram_bytes", sa.BigInteger(), nullable=True),
        sa.Column("gpu_name", sa.String(length=128), nullable=True),
        sa.Column("os_description", sa.String(length=255), nullable=True),
        sa.Column("library_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dataset_id", sa.String(length=128), nullable=True),
        sa.Column("dataset_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("runtime", sa.String(length=64), nullable=True),
        sa.Column("precision", sa.String(length=8), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("results_path", sa.String(length=512), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_benchmark_created", "benchmark_runs", ["created_at"], unique=False)
    op.create_index(
        "ix_benchmark_model", "benchmark_runs", ["model_name", "runtime", "precision"], unique=False
    )
    op.create_index(
        op.f("ix_benchmark_runs_dataset_id"), "benchmark_runs", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_benchmark_runs_owner_id"), "benchmark_runs", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_benchmark_runs_run_id"), "benchmark_runs", ["run_id"], unique=True)
    op.create_table(
        "inference_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("precision", sa.String(length=8), nullable=False),
        sa.Column("queue", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("progress_message", sa.String(length=255), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_jobs_attempts_nonnegative"),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "idempotency_key", name="uq_jobs_owner_idempotency"),
    )
    op.create_index(
        op.f("ix_inference_jobs_asset_id"), "inference_jobs", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_inference_jobs_celery_task_id"), "inference_jobs", ["celery_task_id"], unique=False
    )
    op.create_index(
        op.f("ix_inference_jobs_owner_id"), "inference_jobs", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_inference_jobs_status"), "inference_jobs", ["status"], unique=False)
    op.create_index(
        "ix_jobs_owner_created", "inference_jobs", ["owner_id", "created_at"], unique=False
    )
    op.create_index("ix_jobs_status_queue", "inference_jobs", ["status", "queue"], unique=False)
    op.create_table(
        "inference_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("worker_hostname", sa.String(length=255), nullable=True),
        sa.Column("device", sa.String(length=32), nullable=True),
        sa.Column("device_name", sa.String(length=128), nullable=True),
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("precision", sa.String(length=8), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column("oom_retry", sa.Boolean(), nullable=False),
        sa.Column("retryable_error", sa.Boolean(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("frames_processed", sa.Integer(), nullable=True),
        sa.Column("peak_rss_bytes", sa.BigInteger(), nullable=True),
        sa.Column("peak_vram_bytes", sa.BigInteger(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["inference_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "attempt", name="uq_runs_job_attempt"),
    )
    op.create_index(op.f("ix_inference_runs_job_id"), "inference_runs", ["job_id"], unique=False)
    op.create_index("ix_runs_job_created", "inference_runs", ["job_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_runs_job_created", table_name="inference_runs")
    op.drop_index(op.f("ix_inference_runs_job_id"), table_name="inference_runs")
    op.drop_table("inference_runs")
    op.drop_index("ix_jobs_status_queue", table_name="inference_jobs")
    op.drop_index("ix_jobs_owner_created", table_name="inference_jobs")
    op.drop_index(op.f("ix_inference_jobs_status"), table_name="inference_jobs")
    op.drop_index(op.f("ix_inference_jobs_owner_id"), table_name="inference_jobs")
    op.drop_index(op.f("ix_inference_jobs_celery_task_id"), table_name="inference_jobs")
    op.drop_index(op.f("ix_inference_jobs_asset_id"), table_name="inference_jobs")
    op.drop_table("inference_jobs")
    op.drop_index(op.f("ix_benchmark_runs_run_id"), table_name="benchmark_runs")
    op.drop_index(op.f("ix_benchmark_runs_owner_id"), table_name="benchmark_runs")
    op.drop_index(op.f("ix_benchmark_runs_dataset_id"), table_name="benchmark_runs")
    op.drop_index("ix_benchmark_model", table_name="benchmark_runs")
    op.drop_index("ix_benchmark_created", table_name="benchmark_runs")
    op.drop_table("benchmark_runs")
    op.drop_index("ix_assets_owner_status", table_name="assets")
    op.drop_index(op.f("ix_assets_owner_id"), table_name="assets")
    op.drop_index("ix_assets_owner_created", table_name="assets")
    op.drop_index(op.f("ix_assets_content_sha256"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
